[versions]
metrics = "4.2.37"
jackson = "2.18.2"
dropwizard = "3.0.1"
httpcomponents = "4.5.14"
dogstatsd = "4.4.0"
junit = "4.13.2"
mockito = "5.14.2"
slf4j = "2.0.16"
dnsCacheManipulator = "1.8.3"

[libraries]
dropwizard-metrics-core = { group = "io.dropwizard.metrics", name = "metrics-core", version.ref = "metrics" }
dropwizard-metrics-dropwizard = { group = "io.dropwizard", name = "dropwizard-metrics", version.ref = "dropwizard" }
httpcomponents-fluentHc = { group = "org.apache.httpcomponents", name = "fluent-hc", version.ref = "httpcomponents" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
dogstatsd-client = { group = "com.datadoghq", name = "java-dogstatsd-client", version.ref = "dogstatsd" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
fest-assert-core = { group = "org.easytesting", name = "fest-assert-core", version = "2.0M10" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }
dnsCacheManipulator = { group = "com.alibaba", name = "dns-cache-manipulator", version.ref = "dnsCacheManipulator" }
